FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current files into the container at /app
COPY . /app

RUN pip install -r requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Run the application using Gunicorn
CMD exec gunicorn --bind 0.0.0.0:5000 flask_server:app